### ISSUE TITLE
Items disappearing

### ISSUE THREAD

**Issue by nosycrazy88** [Decept1x/Borderlands-Cleaning-Up-Pandora#1]
When I drop items from my backpack with the mod on, the item instantly disappears. Item doesn't disappear into the void. It is magically gone. Even using the other SDK mod that teleports all items to you does not make it appear.

Side note: Bug also happens Online even when I'm not the host.

**Comment by Decept1x** [comment]
Do you happen to have secondary use bound to "Q"?

**Comment by nosycrazy88** [comment]
> Do you happen to have secondary use bound to "Q"?

yes

**Comment by Decept1x** [comment]
Ah, so I forgot that someone on KBM could bind secondary use to a key that is already bound in the inventory (F, E, Q, etc.) which would cause them to accidentally sell items when attempting to do something else. I made sure that couldn't happen on controller but then completely forgot about KBM (somehow). I plan to fix this in the next update.

**Comment by nosycrazy88** [comment]
> Ah, so I forgot that someone on KBM could bind secondary use to a key that is already bound in the inventory (F, E, Q, etc.) which would cause them to accidentally sell items when attempting to do something else. I made sure that couldn't happen on controller but then completely forgot about KBM (somehow). I plan to fix this in the next update.

Yea after you asked that, I went ingame and changed the keybind to a button on my mouse and the bug no longer happens.

**Comment by nosycrazy88** [comment]
Having it set to the Default Secondary use button was causing it
